name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: false
      - run: cd ./docs && bundle install
      - run: bundle exec jekyll build --config _config.yml
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
